<?php

namespace Database\Seeders;

use App\Models\Core\Category;
use App\Models\Core\Subcategory;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    public function run()
    {
        $categories = [
            'Alimentação' => [
                'Restaurantes',
                'Bares',
                'Padarias',
                'Mercados',
                'Lanchonetes',
                'Pizzarias',
                'Docerias',
                'Açougues',
                'Cafeterias',
                'Food Trucks',
                'Buffets',
                'Salgaderias',
                'Sorveterias',
                'Empórios',
                'Quitandas',
            ],

            'Saúde' => [
                'Clínicas Médicas',
                'Clínicas Odontológicas',
                'Farmácias',
                'Hospitais',
                'Médicos',
                'Psicólogos',
                'Laboratórios',
                'Fisioterapia',
                'Fonoaudiologia',
                'Nutricionistas',
                'Ortopedistas',
                'Oftalmologistas',
                'Clínicas de Estética',
                'Veterinárias',
                'Óticas',
                'Homeopatia',
            ],

            'Beleza & Estética' => [
                'Salões de Beleza',
                'Barbearias',
                'Clínicas de Estética',
                'Spas',
                'Depilação',
                'Manicure e Pedicure',
                'Maquiagem',
                'Design de Sobrancelhas',
                'Massoterapia',
                'Bronzeamento',
                'Cabeleireiros',
            ],

            'Comércio' => [
                'Vestuário Feminino',
                'Vestuário Masculino',
                'Moda Infantil',
                'Calçados',
                'Joalherias',
                'Bijuterias',
                'Eletrônicos',
                'Celulares e Acessórios',
                'Informática',
                'Móveis',
                'Eletrodomésticos',
                'Supermercados',
                'Hortifrúti',
                'Bebidas',
                'Distribuidoras',
                'Papelarias',
                'Livrarias',
                'Floriculturas',
                'Loja de Presentes',
                'Utilidades Domésticas',
                'Loja de R$ 1,99',
                'Pet Shops',
                'Produtos Naturais',
                'Ervanários',
                'Lojas de Brinquedos',
                'Lojas de Games',
                'Loja de Bebê e Gestante',
                'Sex Shops',
            ],

            'Serviços' => [
                'Consultorias',
                'Contabilidade',
                'Advocacia',
                'Marketing e Publicidade',
                'Design Gráfico',
                'Desenvolvimento de Sistemas',
                'TI e Informática',
                'Impressões e Gráficas',
                'Fotografia e Filmagem',
                'Eventos e Cerimonial',
                'Serviços de Limpeza',
                'Dedetização',
                'Reparos Domésticos',
                'Montagem de Móveis',
                'Chaveiros',
                'Costureiras',
                'Aluguel de Equipamentos',
                'Segurança e Monitoramento',
                'Serviços Jurídicos',
                'Coworking',
                'Tradução e Interpretação',
                'Serviços para Pets',
            ],

            'Educação' => [
                'Escolas',
                'Faculdades e Universidades',
                'Cursos Técnicos',
                'Cursos Profissionalizantes',
                'Escolas de Idiomas',
                'Reforço Escolar',
                'Escolas de Música',
                'Autoescolas',
                'Educação Infantil',
                'Aulas Particulares',
                'Cursos Online',
                'Treinamentos Empresariais',
            ],

            'Automotivo' => [
                'Oficinas Mecânicas',
                'Autoelétricas',
                'Funilaria e Pintura',
                'Lava-rápidos',
                'Troca de Óleo',
                'Borracharia',
                'Autopeças',
                'Pneus e Rodas',
                'Concessionárias',
                'Despachantes',
                'Estacionamentos',
                'Guinchos',
                'Locadoras de Veículos',
                'Som Automotivo',
                'Martelinho de Ouro',
                'Blindadoras',
                'Reboques e Carretinhas',
            ],

            'Construção & Reforma' => [
                'Materiais de Construção',
                'Engenharia',
                'Arquitetura',
                'Marmorarias',
                'Vidraçarias',
                'Serralherias',
                'Gesso e Drywall',
                'Pintores',
                'Marceneiros',
                'Pedreiros',
                'Telhados',
                'Hidráulica',
                'Elétrica',
                'Paisagismo',
                'Iluminação',
                'Torneiras e Metais',
                'Lojas de Pisos e Revestimentos',
            ],

            'Casa & Decoração' => [
                'Lojas de Móveis',
                'Colchões',
                'Cortinas e Persianas',
                'Decoração',
                'Utilidades Domésticas',
                'Artigos para Jardim',
                'Ar Condicionado e Ventilação',
                'Aquecedores',
                'Lustres e Iluminação',
                'Enxovais',
                'Tapetes e Carpetes',
            ],

            'Entretenimento & Lazer' => [
                'Cinemas',
                'Teatros',
                'Casas de Show',
                'Parques',
                'Clubes',
                'Baladas',
                'Pubs',
                'Boliches',
                'Jogos e Diversão',
                'Escape Rooms',
                'Paintball',
                'Locação de Brinquedos',
            ],

            'Esportes & Atividades Físicas' => [
                'Academias',
                'Personal Trainers',
                'Estúdios de Pilates',
                'Estúdios de Yoga',
                'Artes Marciais',
                'Crossfit',
                'Zumba e Dança',
                'Lojas de Artigos Esportivos',
                'Ciclismo',
                'Clubes e Quadras',
            ],

            'Indústria' => [
                'Metalúrgicas',
                'Fábricas de Móveis',
                'Confecções',
                'Plásticos',
                'Alimentos',
                'Bebidas',
                'Gráficas Industriais',
                'Calçados',
                'Componentes Eletrônicos',
                'Madeireiras',
                'Indústrias Químicas',
            ],

            'Transporte & Logística' => [
                'Transportadoras',
                'Motoboys',
                'Correios e Encomendas',
                'Mudanças',
                'Fretes',
                'Logística Empresarial',
                'Transporte Escolar',
                'Transporte Executivo',
                'Aluguel de Caminhões',
            ],

            'Agropecuária' => [
                'Fazendas',
                'Agropecuárias',
                'Produtos Veterinários',
                'Sementes e Fertilizantes',
                'Máquinas Agrícolas',
                'Rações',
                'Serviços Rurais',
                'Consultoria Agrícola',
            ],

            'Turismo & Viagens' => [
                'Agências de Viagens',
                'Guias Turísticos',
                'Hotéis',
                'Pousadas',
                'Hostels',
                'Resorts',
                'Campings',
                'Transportes Turísticos',
                'Aluguel por Temporada',
            ],

            'Serviços Públicos & Comunitários' => [
                'Prefeituras',
                'Postos de Saúde',
                'Corpo de Bombeiros',
                'Polícia Militar',
                'Delegacias',
                'Cartórios',
                'Correios',
                'Bancos',
                'INSS',
                'Defesa Civil',
                'Sindicatos',
                'ONGs',
            ],

            'Religião & Espiritualidade' => [
                'Igrejas',
                'Templos',
                'Centros Espíritas',
                'Terreiros',
                'Livrarias Religiosas',
                'Casas de Umbanda/CandomSphere',
            ],

            'Tecnologia' => [
                'Desenvolvedores',
                'Empresas de Software',
                'Suporte Técnico',
                'Automação Residencial',
                'Loja de Computadores',
                'Loja de Celulares',
                'Assistência Técnica',
                'Infraestrutura de Redes',
                'Impressoras e Cartuchos',
            ],
        ];

        foreach ($categories as $categoryName => $subcategories) {
            $category = Category::create([
                'name' => $categoryName,
                'slug' => \Illuminate\Support\Str::slug($categoryName),
                'icon' => 'fas fa-utensils', // Ícone genérico, ajustar conforme categoria
                'order' => array_search($categoryName, array_keys($categories)) + 1,
                'active' => true,
            ]);

            foreach ($subcategories as $subcategoryName) {
                Subcategory::create([
                    'category_id' => $category->id,
                    'name' => $subcategoryName,
                    'slug' => \Illuminate\Support\Str::slug($categoryName . '-' . $subcategoryName), // Adiciona o nome da categoria ao slug
                    'order' => array_search($subcategoryName, $subcategories) + 1,
                    'active' => true,
                ]);
            }
        }
    }
}
